### PR TITLE
Fix some warnings

### PR DESCRIPTION
**Pull request by ygrabit**
and make it compile with different compilers (especially with _USE_MATH_DEFINES)
Thanks

### CODE REVIEW

**Comment by hoene** [comment]
May you ensure that the tests will continue to build?

**Comment by ygrabit** [comment]
No, but our internal tests are still working...
i do not use the cunit, seems not to easy to setup on Windows...

**Comment by hoene** [comment]
This pull request not only fixed warnings but changes the behavior. It needs work.

Please either analyze which effect the reduction in precision has, or remove those changes. Fixing only warnings would be ok.

**Comment by ygrabit** [comment]
I do not know where you see any precision reduction ? it just avoids the compiler to display warnings, The casts are done by the compiler too...

**Comment by hoene** [comment]
Haalo, rufe mich mal an. (07072 8006100)

**Comment by ygrabit** [comment]
please check the email i send to you...

**Comment by hoene** [comment]
The first commit will not do because it changes the syntax of the API. 

If you compare fir with the return value of the interpolation function, you know whether a interpolation has taken place. This is a feature, not a bug.

The second commit is fine and has been already merged.

**Comment by hoene** [comment]
Check this https://github.com/hoene/libmysofa/pull/149 instead

**Pull request closed without merging**
