### PR TITLE
fix big endian convertion of double value

### PR DESCRIPTION
**Pull request by hoene**

### CODE REVIEW

**Comment by Biswa96** [comment]
This causes build failure in Microsoft Windows operating system. The mingw-w64 gcc toolchain shows the following compiler error.

```
ld.exe: reader.c:(.text+0x58d): undefined reference to 'le64toh'
```

**Comment by hoene** [comment]
https://github.com/vysheng/tl-parser/blob/master/portable_endian.h

⁣BlueMail for Android herunterladen ​

**Comment by Biswa96** [comment]
My apology. I did not understand your previous comment. Could you please explain it please?

**Comment by hoene** [comment]
Please check the commit de6e88aa71d44e407b2331059158ed372931aa22

**Comment by Biswa96** [comment]
It fixes building with mingw-w64 gcc toolchain. Thank you.

**Pull request merged**
